# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.registrar.eu/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.registrar.eu", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.registrar.eu/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.registrar.eu")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.domain).to eq("beheeraccount.com")
    expect(subject.domain_id).to eq("3022964043_DOMAIN_COM-VRSN")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2025-09-25 03:55:35 UTC"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2026-02-07 00:38:53 UTC"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2026-09-25 03:55:35 UTC"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("1647")
    expect(subject.registrar.name).to eq("Hosting Concepts B.V. d/b/a Registrar.eu")
    expect(subject.registrar.url).to eq("https://www.registrar.eu")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].id).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].name).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].organization).to eq("")
    expect(subject.registrant_contacts[0].address).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].city).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].zip).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].state).to eq("")
    expect(subject.registrant_contacts[0].country_code).to eq("BE")
    expect(subject.registrant_contacts[0].phone).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].fax).to eq("REDACTED FOR PRIVACY")
    expect(subject.registrant_contacts[0].email).to eq("https://contact-form.registrar.eu/?domainName=beheeraccount.com&purpose=owner")
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(1)
    expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
    expect(subject.admin_contacts[0].id).to eq("REDACTED FOR PRIVACY")
    expect(subject.admin_contacts[0].name).to eq("")
    expect(subject.admin_contacts[0].organization).to eq("")
    expect(subject.admin_contacts[0].address).to eq("")
    expect(subject.admin_contacts[0].city).to eq("")
    expect(subject.admin_contacts[0].zip).to eq("")
    expect(subject.admin_contacts[0].state).to eq("")
    expect(subject.admin_contacts[0].country_code).to eq("")
    expect(subject.admin_contacts[0].phone).to eq("")
    expect(subject.admin_contacts[0].fax).to eq("")
    expect(subject.admin_contacts[0].email).to eq("")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].id).to eq("REDACTED FOR PRIVACY")
    expect(subject.technical_contacts[0].name).to eq("")
    expect(subject.technical_contacts[0].organization).to eq("")
    expect(subject.technical_contacts[0].address).to eq("")
    expect(subject.technical_contacts[0].city).to eq("")
    expect(subject.technical_contacts[0].zip).to eq("")
    expect(subject.technical_contacts[0].state).to eq("")
    expect(subject.technical_contacts[0].country_code).to eq("")
    expect(subject.technical_contacts[0].phone).to eq("")
    expect(subject.technical_contacts[0].fax).to eq("")
    expect(subject.technical_contacts[0].email).to eq("")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(2)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("isaac.ns.cloudflare.com")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ollie.ns.cloudflare.com")
  end
end
