# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.denic.de/de/status_registered_new_disclaimer.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.denic.de", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.denic.de/de/status_registered_new_disclaimer.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.denic.de")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered_new_disclaimer.expected" do
    expect(subject.domain).to eq("your-server.de")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2023-08-02 08:27:56 +02:00"))
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(3)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("ns1.your-server.de")
    expect(subject.nameservers[0].ipv4).to eq("213.133.100.102")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns3.second-ns.de")
    expect(subject.nameservers[1].ipv4).to eq(nil)
    expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[2].name).to eq("ns.second-ns.com")
    expect(subject.nameservers[2].ipv4).to eq(nil)
  end
end
