# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.auda.org.au/au/status_registered_identity_digital.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.auda.org.au", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.auda.org.au/au/status_registered_identity_digital.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.auda.org.au")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered_identity_digital.expected" do
    expect(subject.domain).to eq("jubileeembroideryperth.com.au")
    expect(subject.domain_id).to eq("afacdf7c7ff84c0ba779812791bf6046-AU")
    expect(subject.status).to be_a(Array)
    expect(subject.status.size).to eq(1)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2025-01-30 08:24:09 UTC"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.name).to eq("Synergy Wholesale Accreditations Pty Ltd")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].id).to eq("f02d37d1c8c745d9a30cdda4b6fd2900-AU")
    expect(subject.registrant_contacts[0].name).to eq("Eireann Mahauariki")
    expect(subject.registrant_contacts[0].organization).to eq("EIREANN MAHAUARIKI")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].id).to eq("f0132553139b4bb6b41ea6b359ad3efa-AU")
    expect(subject.technical_contacts[0].name).to eq("Eireann Mahauariki")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(2)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("dns22.webclick.com.au")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("dns21.webclick.com.au")
  end
end
