# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.co.kr/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.co.kr", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.co.kr/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.co.kr")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.domain).to eq("samsung.com")
    expect(subject.domain_id).to eq("1521529_DOMAIN_COM-VRSN")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("1994-11-29 05:00:00 UTC"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2021-06-12 09:11:34 UTC"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2025-11-28 05:00:00 UTC"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("100")
    expect(subject.registrar.name).to eq("Whois Corp.")
    expect(subject.registrar.url).to eq("https://www.whois.co.kr")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].name).to eq("Samsung Electronics CO., Ltd")
    expect(subject.registrant_contacts[0].organization).to eq("Samsung Electronics CO., Ltd")
    expect(subject.registrant_contacts[0].address).to eq("129, Samsung-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do,")
    expect(subject.registrant_contacts[0].city).to eq("Korea")
    expect(subject.registrant_contacts[0].zip).to eq("16677")
    expect(subject.registrant_contacts[0].state).to eq("")
    expect(subject.registrant_contacts[0].country_code).to eq("KR")
    expect(subject.registrant_contacts[0].phone).to eq("+82.27277203")
    expect(subject.registrant_contacts[0].fax).to eq("")
    expect(subject.registrant_contacts[0].email).to eq("ssdomain@samsung.com")
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(1)
    expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
    expect(subject.admin_contacts[0].name).to eq("Samsung Electronics CO., Ltd")
    expect(subject.admin_contacts[0].organization).to eq("Samsung Electronics CO., Ltd")
    expect(subject.admin_contacts[0].address).to eq("129, Samsung-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do,")
    expect(subject.admin_contacts[0].city).to eq("Korea")
    expect(subject.admin_contacts[0].zip).to eq("16677")
    expect(subject.admin_contacts[0].state).to eq("")
    expect(subject.admin_contacts[0].country_code).to eq("KR")
    expect(subject.admin_contacts[0].phone).to eq("+82.27277203")
    expect(subject.admin_contacts[0].fax).to eq("")
    expect(subject.admin_contacts[0].email).to eq("ssdomain@samsung.com")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].name).to eq("Samsung Electronics CO., Ltd")
    expect(subject.technical_contacts[0].organization).to eq("Samsung Electronics CO., Ltd")
    expect(subject.technical_contacts[0].address).to eq("129 Samsung-ro Yeongtong-gu Suwon-si Gyeonggi-do")
    expect(subject.technical_contacts[0].city).to eq("Korea")
    expect(subject.technical_contacts[0].zip).to eq("16677")
    expect(subject.technical_contacts[0].state).to eq("")
    expect(subject.technical_contacts[0].country_code).to eq("KR")
    expect(subject.technical_contacts[0].phone).to eq("+82.27277203")
    expect(subject.technical_contacts[0].fax).to eq("")
    expect(subject.technical_contacts[0].email).to eq("ssdomain@samsung.com")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(6)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("dnssm.samsung.com")
    expect(subject.nameservers[0].ipv4).to eq(nil)
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("dnsst.samsung.com")
    expect(subject.nameservers[1].ipv4).to eq(nil)
    expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[2].name).to eq("dnsst2.samsung.com")
    expect(subject.nameservers[2].ipv4).to eq(nil)
    expect(subject.nameservers[3]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[3].name).to eq("dnssm2.samsung.com")
    expect(subject.nameservers[3].ipv4).to eq(nil)
    expect(subject.nameservers[4]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[4].name).to eq("dns-gi1.samsung.com")
    expect(subject.nameservers[4].ipv4).to eq(nil)
    expect(subject.nameservers[5]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[5].name).to eq("dns-awskr1.samsung.com")
    expect(subject.nameservers[5].ipv4).to eq(nil)
  end
end
