# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.dns.be/be/property_registrant_not_shown.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.dns.be", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.dns.be/be/property_registrant_not_shown.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.dns.be")
    Whois::Parser.parser_for(part)
  end

  it "matches property_registrant_not_shown.expected" do
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].url).to eq("www.dnsbelgium.be")
  end
end
